apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: demo
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
        ports:
          - name: status-port
            port: 15020
            targetPort: 15020
          - name: http2
            port: 80
            nodePort: 31080
            targetPort: 80
          - name: https
            port: 443
            nodePort: 31443
          - name: kiali
            port: 15029
            targetPort: 15029
          - name: prometheus
            port: 15030
            targetPort: 15030
          - name: grafana
            port: 15031
            targetPort: 15031
          - name: tracing
            port: 15032
            targetPort: 15032
          - name: tls
            port: 15443
            targetPort: 15443
