apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: demo
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
        ports:
          - name: status-port
            port: 15020
            targetPort: 15020
          - name: http2
            port: 80
            nodePort: 31080
            targetPort: 80
          - name: https
            port: 443
            nodePort: 31443
