apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: local-istio
  namespace: istio-system
spec:
  profile: demo
  components:
    ingressGateways:
      - name: ingressgateway
        namespace: istio-system
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
              - name: status-port
                port: 15020
                targetPort: 15020
              - name: http2
                port: 80
                nodePort: 31080
                targetPort: 80
              - name: https
                port: 443
                nodePort: 31443
