apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  gateways:
    - ingressgateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: "/kiali"
      route:
        - destination:
            host: kiali
